# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7106aabefbc1d8756341e28b66264f43"
name = "Lucidly"
application_url = "https://lucidly.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"

[access_scopes]
scopes = "read_orders,read_all_orders,read_customers,read_products"

[auth]
redirect_urls = [ "https://lucidly.fly.dev/auth/callback", "https://lucidly.fly.dev/auth/shopify/callback", "https://lucidly.fly.dev/api/auth/callback" ]

[access.customer_data]
reason = "App provides order attribution and customer lifetime value analytics"

  [[access.customer_data.fields]]
  data_category = "name"

  [[access.customer_data.fields]]
  data_category = "email"

  [[access.customer_data.fields]]
  data_category = "orders"
